=== intasect/cordyssapcon/trunk/src/cws/SAP R3 Connector/Static Files/BAC/SAP/schemas/configuration.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://sapconnector.cordys.com/2.0/configuration"
	targetNamespace="http://sapconnector.cordys.com/2.0/configuration" elementFormDefault="qualified">
	<element name="connection" type="tns:ctConnection"></element>

	<complexType name="ctConnection">
		<sequence>
			<element name="sapserver" type="string" maxOccurs="1"
				minOccurs="1">
			</element>
			<element name="cachedirectory" type="string" maxOccurs="1"
				minOccurs="1">
			</element>
			<element name="fallbackToSystemUser" type="boolean" maxOccurs="1" minOccurs="1" default="true"></element>
			<element name="alwaysUseMappedUser" type="boolean" maxOccurs="1" minOccurs="1" default="false"></element>
			<choice maxOccurs="1" minOccurs="1">
				<element name="jco" type="tns:ctJCO"></element>
				<element name="bc" type="tns:ctBC"></element>
			</choice>
		</sequence>
	</complexType>

	<complexType name="ctJCO">
		<sequence>
			<element name="client" type="int" maxOccurs="1" minOccurs="1"></element>
			<element name="sysnum" type="string" maxOccurs="1" minOccurs="1"></element>
			<element name="language" type="string" maxOccurs="1"
				minOccurs="1"></element>
			<element name="userid" type="string" maxOccurs="1" minOccurs="1"></element>
			<element name="password" type="string" maxOccurs="1"
				minOccurs="1"></element>
			<element name="idocservers" type="string" maxOccurs="1"
				minOccurs="0" default="1"></element>
			<element name="gwserv" type="string" maxOccurs="1" minOccurs="0"></element>
			<element name="progID" type="int" maxOccurs="1" minOccurs="1"></element>
			<element name="maxCons" type="int" maxOccurs="1" minOccurs="1"
				default="1"></element>
		</sequence>
	</complexType>

	<complexType name="ctBC">
		<sequence>
			<element name="bcserver" type="string" maxOccurs="1"
				minOccurs="1"></element>
			<element name="bcport" type="int" maxOccurs="1" minOccurs="1"></element>
			<element name="protocol" type="string" maxOccurs="1"
				minOccurs="1"></element>
			<element name="keystoreloc" type="string" maxOccurs="1"
				minOccurs="1"></element>
			<element name="keystorepassword" type="string" maxOccurs="1"
				minOccurs="0" default="1"></element>
			<element name="type" type="string" maxOccurs="1" minOccurs="0"></element>
			<element name="provider" type="string" maxOccurs="1"
				minOccurs="1"></element>
			<element name="bapiinvokeurl" type="string" maxOccurs="1"
				minOccurs="1" default="1"></element>
			<element name="rfcinvokeurl" type="string" maxOccurs="1"
				minOccurs="1" default="1"></element>
			<element name="idocinvokeurl" type="string" maxOccurs="1"
				minOccurs="1" default="1"></element>
		</sequence>
	</complexType>
</schema>

=== intasect/cordyssapcon/tags/2.0.4/Test/Utils/NewFile.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:connection xmlns:tns="http://sapconnector.cordys.com/2.0/configuration" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://sapconnector.cordys.com/2.0/configuration ../src/cws/SAP_R3_M_BOP4/Static Files/BAC/SAP/schemas/configuration.xsd ">
  <tns:sapserver>1</tns:sapserver>
		<tns:jco>
			<tns:client>1</tns:client>
			<tns:sysnum>1</tns:sysnum>
			<tns:language>EN</tns:language>
			<tns:cachedirectory>c:\te</tns:cachedirectory>
			<tns:userid>1</tns:userid>
			<tns:password>MQ==</tns:password>
			<tns:idocservers>1</tns:idocservers>
			<tns:gwserv>1</tns:gwserv>
			<tns:progID>1</tns:progID>
			<tns:maxCons>10</tns:maxCons>
		</tns:jco>
</tns:connection>
